export const EASY = 'easy';
export const HARD = 'hard';

export const easy = [
    "a little bit",
    "a pity",
    "a shame",
    "a variety of sth/sb",
    "abroad",
    "accent",
    "accept",
    "accident",
    "accompany",
    "according to",
    "ache",
    "achieve",
    "across",
    "activity",
    "adequate",
    "adjective",
    "adjust",
    "admire",
    "admit",
    "advantage",
    "adventure",
    "adverb",
    "advertise",
    "affect",
    "affect",
    "afraid",
    "afterwards/afterward",
    "aim",
    "airport",
    "album",
    "alive",
    "all the best",
    "along",
    "aloud",
    "alter",
    "although",
    "amazing",
    "among",
    "amount",
    "and",
    "announce",
    "anticipate",
    "anymore",
    "anyway",
    "apartment",
    "apology",
    "appointment",
    "approximately",
    "Arab",
    "area",
    "army",
    "around",
    "around",
    "arrival",
    "article",
    "as much / quickly / soon, etc. as possible",
    "as soon as",
    "as you know",
    "ask",
    "at",
    "at first",
    "at present",
    "at the moment",
    "attention",
    "Attention!",
    "attitude",
    "audience",
    "author",
    "available",
    "awake",
    "away",
    "back",
    "backward/backwards",
    "bad",
    "baker",
    "balloon",
    "bar",
    "barbecue",
    "baseball",
    "basket",
    "battery",
    "battle",
    "be able to do sth",
    "be crazy about sb/sth",
    "be located in / near / on / etc.",
    "be made of",
    "be off",
    "be responsible for sb/sth/doing sth",
    "be supposed to do sth",
    "be unable to do sth",
    "be used to sb/sth/doing sth",
    "be willing (to do sth)",
    "be worth",
    "be worth it",
    "be wrong",
    "be",
    "bear",
    "beauty",
    "Bedouin",
    "bedtime",
    "behave",
    "behavior",
    "belief",
    "belong to sb",
    "below",
    "beside",
    "best wishes",
    "Bible",
    "blanket",
    "blond/blonde",
    "blood",
    "blow",
    "body",
    "boil",
    "book",
    "boot",
    "border",
    "borrow",
    "boss",
    "bowl",
    "boyfriend",
    "brain",
    "branch",
    "brave",
    "break",
    "break down",
    "bridge",
    "bring back sth or bring sth back",
    "broken",
    "burn",
    "business",
    "but",
    "by",
    "by",
    "by mistake",
    "by the way",
    "café",
    "calendar",
    "call",
    "call back (sb) or call (sb) back",
    "calm",
    "can",
    "can afford",
    "cancer",
    "candle",
    "can't stand sb/sth",
    "can't wait",
    "cap",
    "capital",
    "card",
    "care",
    "care",
    "careless",
    "carrot",
    "carry",
    "carry on",
    "carry out",
    "case",
    "case",
    "cash",
    "castle",
    "catch",
    "catch fire",
    "Catholic",
    "ceiling",
    "celebrate",
    "cent",
    "centimeter",
    "century",
    "certain",
    "champion",
    "chance",
    "change",
    "change",
    "channel",
    "character",
    "charge",
    "chat",
    "check",
    "check-in (desk)",
    "chef",
    "childhood",
    "chip",
    "choice",
    "Christian",
    "church",
    "Circassian",
    "circus",
    "clap",
    "clear",
    "click",
    "close",
    "closing time",
    "coach",
    "code",
    "coin",
    "cold",
    "comb",
    "combine",
    "come down",
    "comma",
    "communication",
    "compare",
    "compete",
    "complete",
    "concert",
    "confident",
    "Congratulations!",
    "connection",
    "contact",
    "contents",
    "context",
    "continue",
    "contract",
    "control",
    "convince",
    "cooking",
    "copy",
    "corn",
    "correct",
    "cotton",
    "cough",
    "could",
    "course",
    "cousin",
    "crazy",
    "cream",
    "create",
    "credit",
    "crisp",
    "crossing",
    "cry",
    "culture",
    "cupboard",
    "curtain",
    "cut up sth or cut sth up",
    "daily",
    "danger",
    "date of birth",
    "deal",
    "death",
    "definitely",
    "degree",
    "delay",
    "demand",
    "dentist",
    "department store",
    "dependent",
    "description",
    "desert",
    "dessert",
    "destroy",
    "develop",
    "diary",
    "dictation",
    "differently",
    "difficulty",
    "dig",
    "digital",
    "diploma",
    "direct",
    "directions",
    "director",
    "dirt",
    "disappear",
    "discount",
    "discover",
    "discuss",
    "disease",
    "dish",
    "distance",
    "doubt",
    "drawer",
    "dream",
    "drive",
    "drop",
    "drum",
    "Druze",
    "duck",
    "due",
    "duty",
    "each other",
    "earn",
    "earring",
    "Earth",
    "education",
    "effect",
    "election",
    "electricity",
    "elevator",
    "email",
    "emoji",
    "employ",
    "ending",
    "enemy",
    "energy",
    "energy",
    "enter",
    "envelope",
    "environment",
    "equipment",
    "error",
    "euro",
    "even",
    "event",
    "everyday",
    "exact",
    "examine",
    "excited",
    "exercise",
    "exit",
    "expect",
    "expensive",
    "experience",
    "explanation",
    "explore",
    "express",
    "extremely",
    "face",
    "factory",
    "fair",
    "fair",
    "fairly",
    "fall",
    "fall down",
    "FALSE",
    "familiar",
    "fan",
    "fantastic",
    "fashion",
    "fear",
    "feather",
    "feel",
    "fight",
    "fill in/out sth or fill sth in/out",
    "fine",
    "fine",
    "first of all",
    "fish",
    "fishing",
    "fit",
    "fix",
    "flag",
    "flat",
    "flight",
    "flour",
    "fog",
    "follow",
    "for",
    "for sale",
    "form",
    "forward",
    "frame",
    "free",
    "free",
    "freedom",
    "fresh",
    "fresh",
    "fresh air",
    "friendship",
    "full stop",
    "fully",
    "fur",
    "furniture",
    "gain",
    "gap",
    "garbage",
    "gas",
    "gas/gasoline",
    "gather",
    "general",
    "geography",
    "get back sth or get sth back",
    "get married",
    "get to know sb/sth",
    "get together",
    "girlfriend",
    "give back sth or give sth back",
    "glove",
    "go abroad",
    "go back",
    "god",
    "gold",
    "gold",
    "golden",
    "good-looking",
    "government",
    "grammar",
    "great",
    "great",
    "grow up",
    "guard",
    "guest",
    "guest",
    "guide",
    "guy",
    "gym",
    "habit",
    "hall",
    "hand sth out or hand out sth",
    "handbag",
    "hard",
    "hardly",
    "hardly ever",
    "hate",
    "have (got) to do sth",
    "head",
    "head back / down / towards, etc",
    "headache",
    "health",
    "healthy",
    "hear from sb",
    "hearing",
    "heart",
    "heart",
    "heavily",
    "helpful",
    "hero",
    "herself",
    "hide",
    "high",
    "highway",
    "himself",
    "history",
    "hobby",
    "honey",
    "horrible",
    "housewife",
    "How do you do?",
    "How/What about?",
    "however",
    "hug",
    "human",
    "hundreds",
    "hunger",
    "hunting",
    "hurry",
    "hurt",
    "idea",
    "identify",
    "if",
    "if you like",
    "ignore",
    "ill",
    "I'm afraid …",
    "image",
    "imagine",
    "imagine",
    "immediate",
    "importance",
    "important",
    "impossible",
    "improve",
    "in",
    "in",
    "in addition (to)",
    "in case of sth",
    "in front",
    "in love",
    "in the end",
    "in time",
    "in two/half",
    "included",
    "increase",
    "industry",
    "inform",
    "information technology",
    "ingredient",
    "inner",
    "insect",
    "inside",
    "instrument",
    "insult",
    "interest",
    "international",
    "interval",
    "introduce",
    "invent",
    "involve",
    "Islam",
    "it looks like/as if",
    "it/that depends",
    "item",
    "itself",
    "jail",
    "jazz",
    "Jew",
    "jewelry",
    "job",
    "join",
    "joke",
    "joy",
    "Judaism",
    "judge",
    "just",
    "just",
    "just a moment",
    "kick",
    "kilogram",
    "kilometer",
    "kite",
    "know",
    "lack of sth",
    "lake",
    "lamp",
    "land",
    "land",
    "laptop",
    "largely",
    "latest",
    "laugh at sb/sth",
    "law",
    "lawyer",
    "lead",
    "leaf",
    "leave",
    "leave",
    "leave out sb/sth or leave sb/sth out",
    "left",
    "lemon",
    "lemonade",
    "lend",
    "let sb know (sth)",
    "level",
    "level",
    "library",
    "licence/license",
    "lick",
    "lift",
    "lift",
    "like",
    "limit",
    "line",
    "lion",
    "liter",
    "local",
    "locate",
    "lock",
    "long",
    "look around/round",
    "look like",
    "look nice/strange, etc.",
    "Look out!",
    "look up sth or look sth up",
    "lose",
    "loud",
    "love",
    "love / (with) love from / all my love/lots of love",
    "luck",
    "luck",
    "lucky",
    "luggage",
    "machine",
    "magic",
    "magic",
    "mail",
    "main",
    "mainly",
    "make a face",
    "make sure (that)",
    "manage",
    "map",
    "marry",
    "match",
    "maximum",
    "measure",
    "medal",
    "medicine",
    "medicine",
    "medium",
    "meet",
    "memory",
    "midday",
    "midnight",
    "military",
    "mind",
    "minimum",
    "mirror",
    "miss",
    "modern",
    "moment",
    "Moslem/Muslim",
    "mosque",
    "most",
    "mostly",
    "mouse",
    "move",
    "move in/move out",
    "murder",
    "muscle",
    "musical",
    "musician",
    "myself",
    "name",
    "nation",
    "nationality",
    "natural",
    "near",
    "nearby",
    "necessary",
    "necklace",
    "neither",
    "never mind",
    "normally",
    "note",
    "nothing",
    "notice",
    "noticeboard",
    "noun",
    "object",
    "obvious",
    "of course",
    "of course not",
    "offer",
    "officer",
    "oh",
    "old",
    "on fire",
    "on foot",
    "on offer",
    "on time",
    "one",
    "one another",
    "one day",
    "open",
    "operate",
    "opinion",
    "opportunity",
    "option",
    "or something (like that)",
    "order",
    "ordinary",
    "organization",
    "organize",
    "original",
    "ourselves",
    "out of order",
    "over",
    "over",
    "owe",
    "p.m.",
    "package",
    "pain",
    "pajamas/pyjamas",
    "palace",
    "parcel",
    "part of sth",
    "pass",
    "passenger",
    "passport",
    "path",
    "patient",
    "pattern",
    "peace",
    "pear",
    "pension",
    "pepper",
    "performance",
    "period",
    "personal",
    "petrol",
    "physical",
    "physics",
    "piano",
    "pick up sb/sth or pick sb/sth up",
    "piece",
    "pillow",
    "play",
    "playground",
    "please",
    "pleased",
    "pleasure",
    "poem",
    "point",
    "point",
    "polite",
    "poor",
    "popcorn",
    "position",
    "possibility",
    "post",
    "potential",
    "powerful",
    "preparation",
    "press",
    "prison",
    "private",
    "produce",
    "professional",
    "program",
    "promise",
    "property",
    "proposal",
    "protect",
    "proud",
    "prove",
    "public",
    "puppy",
    "pure",
    "purple",
    "purpose",
    "purse",
    "push",
    "put off sb or put sb off (sb/sth doing sth)",
    "put off sth/doing sth or put sth off",
    "put on sth or put sth on (music/movie)",
    "put on sth or put sth on (clothes)",
    "put sb up",
    "put sth (down) in writing",
    "put sth together or put together sth",
    "puzzle",
    "quality",
    "quantity",
    "question mark",
    "quietly",
    "quite",
    "race",
    "range",
    "rat",
    "reach",
    "reaction",
    "read out sth or read sth out",
    "real",
    "realize",
    "really",
    "really",
    "reasonable",
    "receive",
    "recent",
    "recognize",
    "record",
    "reduce",
    "refer to sb/sth",
    "relations",
    "religion",
    "remain",
    "remove",
    "repair",
    "reply",
    "resource",
    "responsible",
    "rich",
    "right away / now / after",
    "ring",
    "rock",
    "rock",
    "role",
    "roll",
    "round",
    "row",
    "safe",
    "salty",
    "sauce",
    "sausage",
    "save",
    "scarf",
    "scientific",
    "scissors",
    "scooter/electric scooter",
    "score",
    "scream",
    "season",
    "secret",
    "secretary",
    "seem happy / a nice person, etc.",
    "select",
    "selfie",
    "sense",
    "separate",
    "serve",
    "set",
    "sex",
    "shadow",
    "shake hands",
    "shape",
    "share",
    "sheet",
    "shelf",
    "ship",
    "shoot",
    "shopping",
    "shout",
    "shut",
    "shy",
    "side",
    "sight",
    "silence",
    "silly",
    "silver",
    "similar",
    "simple",
    "single",
    "sink",
    "sir",
    "sitting room",
    "situation",
    "skate",
    "ski",
    "sleep",
    "slice",
    "slim",
    "smart",
    "smell",
    "smoke",
    "so",
    "so far",
    "soccer",
    "soft",
    "soft drink",
    "software",
    "soldier",
    "somehow",
    "sort",
    "space",
    "speech",
    "spot",
    "staff",
    "stage",
    "standard",
    "star",
    "state",
    "stay",
    "steam",
    "step",
    "stomach",
    "stomach ache",
    "stone",
    "stop",
    "stop",
    "story",
    "straight",
    "strawberry",
    "strength",
    "strongly",
    "study",
    "style",
    "subject",
    "succeed",
    "such a(n)",
    "such as",
    "suggest",
    "suit",
    "sunglasses",
    "suppose",
    "surely",
    "surprise",
    "swim",
    "synagogue",
    "take",
    "take a break/rest, etc.",
    "take an exam",
    "take sb/sth seriously",
    "take sth back or take back sth",
    "take sth out or take out sth",
    "taste",
    "teaching",
    "team",
    "tear",
    "teaspoon",
    "technology",
    "teenager",
    "tell",
    "tell sb to do sth",
    "tend to do sth",
    "terrible",
    "terrible",
    "text",
    "thanks",
    "that",
    "that",
    "that's all right",
    "the air",
    "the army",
    "the best",
    "the day after tomorrow",
    "the day before yesterday",
    "the dishes",
    "the first",
    "the matter",
    "the most attractive / important/popular, etc.",
    "the same",
    "the young",
    "theater",
    "their",
    "themselves",
    "then",
    "therefore",
    "there's no doubt",
    "thick",
    "think of sth",
    "think",
    "though",
    "thought",
    "threat",
    "throat",
    "thumb",
    "thunder",
    "tidy up (sth) or tidy (sth) up",
    "tie",
    "tie",
    "time",
    "timetable",
    "tin",
    "tiny",
    "title",
    "to",
    "toast",
    "today",
    "toe",
    "together",
    "tongue",
    "too bad",
    "toothache",
    "toothpaste",
    "top",
    "topic",
    "total",
    "touch",
    "tour",
    "toward",
    "towel",
    "tower",
    "trade",
    "traffic",
    "train",
    "tram",
    "traveler",
    "treat",
    "trouble",
    "trousers",
    "truck",
    "trust",
    "try",
    "try on sth or try sth on",
    "try/do one's best",
    "tune",
    "turn",
    "turning",
    "ugly",
    "understanding",
    "uniform",
    "unit",
    "unless",
    "unnecessary",
    "unpleasant",
    "until",
    "up the street/road, etc.",
    "use",
    "used to do/be sth",
    "usual",
    "video",
    "virus",
    "visit",
    "voice",
    "volume",
    "vote",
    "warm",
    "warn",
    "watch out",
    "wave",
    "we",
    "website",
    "weekly",
    "weight",
    "well",
    "well-made",
    "wet",
    "What is sb/sth like?",
    "wheel",
    "whenever",
    "whether",
    "whether … or",
    "which",
    "whose",
    "Why don't you?/ Why not do sth?",
    "Why not?",
    "widely",
    "wild",
    "wild",
    "window",
    "wing",
    "wish",
    "wonder",
    "wool",
    "work",
    "worried",
    "worse",
    "would love sth",
    "would love to (do sth)",
    "would prefer",
    "wow!",
    "wrap sth up or wrap up sth",
    "wrong",
    "you know",
    "your big brother / sister",
    "yourself",
    "yourselves"
]

export const easy_hebrew = [
    `מעט`,
    `חבל`,
    `חבל`,
    `מבחר של  משהו`,
    `חוץ לארץ`,
    `מבטא`,
    `לקבל`,
    `תאונה`,
    `ללוות`,
    `לפי`,
    `כאב`,
    `להשיג`,
    `מעבר ל`,
    `פעילות`,
    `הולם`,
    `שם תואר`,
    `להסתגל`,
    `להעריץ`,
    `להתוודות`,
    `יתרון`,
    `הרפתקה`,
    `תואר הפועל`,
    `לפרסם`,
    `להשפיע`,
    `לרגש`,
    `פוחד`,
    `לאחר מכן`,
    `להתכוון, מטרה`,
    `שדה תעופה`,
    `אלבום`,
    `בחיים`,
    `כל טוב`,
    `לצד`,
    `בקול רם`,
    `לשנות`,
    `אף על פי ש`,
    `מדהים`,
    `בקרב`,
    `כמות`,
    `ו' החיבור`,
    `להודיע`,
    `לצפות`,
    `כבר לא`,
    `בכל אופן`,
    `דירה`,
    `התנצלות`,
    `פגישה, תור`,
    `בערך`,
    `ערבי`,
    `אזור`,
    `צבא`,
    `ליד`,
    `בערך`,
    `הגעה, נחיתה`,
    `כתבה`,
    `כפי ש`,
    `בהקדם`,
    `כפי שאת/ה יודע/ת`,
    `להזמין`,
    `ב...`,
    `בתחילה`,
    `כיום`,
    `כרגע`,
    `תשומת לב`,
    `שימו לב!`,
    `גישה`,
    `קהל`,
    `סופר, מחבר`,
    `זמין`,
    `ער`,
    `הרחק`,
    `מאחורי`,
    `אחורה`,
    `רע`,
    `אופה`,
    `בלון, כדור פורח`,
    `מוט`,
    `מנגל`,
    `בייסבול`,
    `סל`,
    `סוללה`,
    `קרב`,
    `להיות יכול לעשות משהו`,
    `לאהוב מאוד משהו`,
    `להימצא ב/ליד/על/ וכו'`,
    `להיות עשוי ממשהו`,
    `להסתלק`,
    `להיות אחראי`,
    `להיות אמור לעשות`,
    `לא להיות מסוגל לעשות`,
    `להיות רגיל למשהו/לעשות משהו`,
    `להיות מוכן לעשות משהו`,
    `להיות בעל ערך`,
    `להיות ראוי`,
    `לטעות`,
    `להיות משהו`,
    `דוב`,
    `יופי`,
    `בדואי`,
    `שעת השינה`,
    `להתנהג`,
    `התנהגות`,
    `אמונה`,
    `שייך למישהו`,
    `פחות`,
    `לצד`,
    `ברכות מקרב לב`,
    `תנ"ך`,
    `שמיכה`,
    `בלונדיני`,
    `דם`,
    `לנשוב, לנשוף`,
    `גופה`,
    `לרתוח`,
    `לקבוע, להזמין`,
    `מגף`,
    `גבול`,
    `לקחת בהשאלה`,
    `מנהל`,
    `קערה`,
    `חבר, בן זוג`,
    `שכל`,
    `ענף`,
    `אמיץ`,
    `הפסקה`,
    `להישבר`,
    `גשר`,
    `להחזיר`,
    `שבור`,
    `שרוף`,
    `עסק`,
    `חוץ מ...`,
    `מאת`,
    `עד`,
    `בטעות`,
    `דרך אגב`,
    `בית קפה`,
    `לוח שנה`,
    `לכנות`,
    `להתקשר בחזרה`,
    `רגוע`,
    `פחית`,
    `יכול להרשות לעצמו`,
    `סרטן`,
    `נר`,
    `לא לסבול מישהו/משהו`,
    `לא להיות מסוגל להתאפק`,
    `כובע מצחייה`,
    `עיר בירה`,
    `כרטיס, קלף`,
    `תשומת לב`,
    `לאהוב`,
    `פזיז`,
    `גזר`,
    `לשאת`,
    `להמשיך`,
    `לבצע`,
    `מקרה`,
    `קופסה`,
    `כסף מזומן`,
    `טירה`,
    `לחלות`,
    `להישרף`,
    `קתולי`,
    `תקרה`,
    `לחגוג`,
    `סנט`,
    `סנטימטר`,
    `מאה`,
    `ודאי`,
    `אלוף`,
    `אפשרות`,
    `להחליף בגדים`,
    `שינוי`,
    `ערוץ`,
    `דמות`,
    `לחייב`,
    `לשוחח, שיחה`,
    `לבדוק, בדיקה`,
    `דלפק קבלה`,
    `שף`,
    `ילדות`,
    `שבב`,
    `בחירה`,
    `נוצרי`,
    `כנסייה`,
    `צ'רקסי`,
    `קרקס`,
    `למחוא כפיים`,
    `ברור`,
    `להקיש, הקשה`,
    `קרוב`,
    `שעת סגירה`,
    `אוטובוס, קרון רכבת, כרכרה`,
    `קוד`,
    `מטבע`,
    `הצטננות`,
    `מסרק , לסרק`,
    `לשלב`,
    `להירגע`,
    `פסיק`,
    `תקשורת`,
    `להשוות`,
    `להתחרות`,
    `מוחלט`,
    `הופעה`,
    `בטוח`,
    `מזל טוב!`,
    `קשר`,
    `קשר, ליצור קשר`,
    `תוכן`,
    `הקשר`,
    `להמשיך`,
    `חוזה`,
    `שליטה, לשלוט`,
    `לשכנע`,
    `בישול`,
    `העתק להעתיק`,
    `תירס`,
    `לתקן`,
    `כותנה`,
    `להשתעל, שיעול`,
    `היה יכול`,
    `קורס, שיעור`,
    `בן דוד`,
    `משוגע`,
    `שמנת`,
    `ליצור`,
    `אשראי`,
    `פריך, חטיף צ'יפס`,
    `מעבר`,
    `לבכות, בכי`,
    `תרבות`,
    `ארון`,
    `וילון, מסך`,
    `לחתוך`,
    `יומי`,
    `סכנה`,
    `תאריך לידה`,
    `עסקה`,
    `מוות`,
    `לחלוטין`,
    `מעלה`,
    `עיכוב, לעכב`,
    `לדרוש, דרישה`,
    `רופא שיניים`,
    `מחלקה`,
    `תלוי`,
    `תיאור`,
    `מדבר`,
    `קינוח`,
    `להרוס`,
    `להתפתח`,
    `יומן`,
    `הכתבה`,
    `באופן שונה`,
    `קושי`,
    `לחפור`,
    `דיגיטלי`,
    `תעודה`,
    `להנחות`,
    `הנחיות`,
    `במאי`,
    `לכלוך`,
    `להיעלם`,
    `הנחה`,
    `לגלות`,
    `לדון`,
    `מחלה`,
    `כלי אוכל`,
    `מרחק`,
    `ספק`,
    `מגירה`,
    `חלום, לחלום`,
    `נסיעה`,
    `ליפול`,
    `תוף`,
    `דרוזי`,
    `ברווז`,
    `בגלל`,
    `חובה`,
    `זה את זה`,
    `להרוויח`,
    `עגיל`,
    `כדור הארץ`,
    `חינוך`,
    `השפעה`,
    `בחירות`,
    `חשמל`,
    `מעלית`,
    `דואר אלקטרוני`,
    `אימוג'י, סמלון`,
    `להעסיק`,
    `סיום`,
    `אויב`,
    `כוח`,
    `אנרגיה`,
    `להיכנס`,
    `מעטפה`,
    `סביבה`,
    `ציוד`,
    `שגיאה`,
    `יורו`,
    `אף ש...`,
    `אירוע`,
    `יומיומי`,
    `מדויק`,
    `לבדוק`,
    `נרגש`,
    `תרגיל`,
    `יציאה`,
    `לצפות`,
    `יקר`,
    `ניסיון`,
    `הסבר`,
    `לחקור`,
    `להביע`,
    `מאוד`,
    `לפנות לכיוון`,
    `מפעל`,
    `בהיר`,
    `הוגן`,
    `בהגינות`,
    `סתיו`,
    `ליפול`,
    `לא נכון`,
    `מוכר`,
    `אוהד`,
    `דמיוני`,
    `אופנה`,
    `פחד`,
    `נוצה`,
    `להרגיש`,
    `להילחם, קרב`,
    `למלא`,
    `מצוין`,
    `בריא`,
    `קודם כל`,
    `לדוג`,
    `דיג`,
    `להתאים`,
    `לתקן`,
    `דגל`,
    `שטוח`,
    `טיסה`,
    `קמח`,
    `ערפל`,
    `לציית`,
    `למשך`,
    `למכירה`,
    `סוג`,
    `קדימה`,
    `מסגרת`,
    `חינם`,
    `פנוי`,
    `חופש`,
    `טרי`,
    `רענן`,
    `אוויר צח`,
    `חברות`,
    `נקודה בסוף משפט`,
    `לחלוטין`,
    `פרווה`,
    `ריהוט`,
    `לצבור`,
    `פער`,
    `אשפה`,
    `גז`,
    `דלק`,
    `לאסוף`,
    `כללי`,
    `גאוגרפיה`,
    `להתנקם`,
    `להתחתן`,
    `להתוודע`,
    `לחבור`,
    `חברה, בת זוג`,
    `להחזיר`,
    `כפפה`,
    `לנסוע לחו"ל`,
    `לחזור`,
    `אלוהים`,
    `זהב`,
    `זהוב`,
    `מוזהב`,
    `יפה`,
    `ממשלה`,
    `דקדוק`,
    `גדול`,
    `מצוין`,
    `להתבגר`,
    `שומר`,
    `אורח`,
    `לקוח`,
    `מדריך, להדריך`,
    `בחור`,
    `חדר כושר`,
    `הרגל`,
    `אולם`,
    `לחלק`,
    `תיק`,
    `קשה`,
    `בקושי`,
    `לעיתים רחוקות`,
    `שנאה`,
    `להיות חייב לעשות משהו`,
    `להוביל`,
    `לפנות`,
    `כאב ראש`,
    `בריאות`,
    `בריא`,
    `לשמוע ממישהו`,
    `שמיעה`,
    `emotion`,
    `צורת לב`,
    `במידה רבה`,
    `מועיל`,
    `גיבור`,
    `עצמה`,
    `להחביא`,
    `גבוה`,
    `כביש ראשי`,
    `עצמו`,
    `היסטוריה`,
    `תחביב`,
    `דבש`,
    `נוראי`,
    `עקרת בית`,
    `מה שלומך?`,
    `מה בעניין?`,
    `עם זאת`,
    `לחבק, חיבוק`,
    `אנושי`,
    `מאות`,
    `רעב`,
    `ציד`,
    `למהר, מהירות`,
    `להכאיב`,
    `רעיון`,
    `לזהות`,
    `אם תרצה`,
    `אם תרצה`,
    `להתעלם`,
    `חולה`,
    `חוששני`,
    `דימוי`,
    `להאמין`,
    `לדמיין`,
    `מיידי`,
    `חשיבות`,
    `חשוב`,
    `בלתי אפשרי`,
    `לשפר`,
    `במהלך`,
    `ב`,
    `בנוסף`,
    `במקרה של`,
    `לפני`,
    `מאוהב`,
    `בסוף`,
    `בזמן`,
    `לשניים, לחצי`,
    `כלול`,
    `להגדיל, גדילה`,
    `תעשייה`,
    `להודיע`,
    `טכנולוגיית מידע`,
    `רכיב`,
    `פנימי`,
    `חרק`,
    `בפנים`,
    `כלי`,
    `עלבון`,
    `עניין`,
    `בינלאומי`,
    `מרווח`,
    `להציג מישהו למישהו`,
    `להמציא`,
    `לערב`,
    `איסלאם`,
    `נראה כאילו`,
    `זה תלוי`,
    `חפץ`,
    `עצמו`,
    `כלא`,
    `ג'ז`,
    `יהודי`,
    `תכשיטים`,
    `עבודה`,
    `להצטרף`,
    `בדיחה`,
    `אושר`,
    `יהדות`,
    `שופט לשפוט`,
    `רק`,
    `בלבד`,
    `רק רגע`,
    `בעיטה`,
    `קילוגרם`,
    `קילומטר`,
    `עפיפון`,
    `לזהות`,
    `חוסר במשהו`,
    `אגם`,
    `מנורה`,
    `אדמה`,
    `לנחות`,
    `מחשב נייד`,
    `בעיקר`,
    `החדש ביותר`,
    `ללעוג למישהו`,
    `חוק`,
    `עורך דין`,
    `להוביל`,
    `עלה`,
    `לעזוב`,
    `להשאיר`,
    `להשמיט`,
    `שמאל`,
    `לימון`,
    `לימונדה`,
    `להשאיל`,
    `ליידע`,
    `דרגה`,
    `רמה`,
    `ספרייה`,
    `רישיון`,
    `ללקק`,
    `להרים`,
    `מעלית`,
    `כמו`,
    `להגביל, גבול`,
    `תור`,
    `אריה`,
    `ליטר`,
    `מקומי`,
    `למקם`,
    `מנעול, לנעול`,
    `מפורט`,
    `להתבונן`,
    `להידמות`,
    `להיראות`,
    `זהירות!`,
    `לחפש פריט ברשימה`,
    `לאבד`,
    `קולני`,
    `אהבה`,
    `באהבה`,
    `מזל`,
    `הצלחה`,
    `בר מזל`,
    `מטען`,
    `מכונה`,
    `כישוף`,
    `קסם`,
    `דואר`,
    `עיקרי`,
    `בעיקר`,
    `לעטות הבעה`,
    `לוודא`,
    `להצליח`,
    `מפה`,
    `להתחתן`,
    `גפרור`,
    `מקסימום, מירבי`,
    `למדוד`,
    `מדליה`,
    `תרופה`,
    `רפואה`,
    `בינוני, אמצע`,
    `לפגוש`,
    `זיכרון`,
    `אמצע היום`,
    `חצות`,
    `צבאי`,
    `חשיבה`,
    `מינימום`,
    `ראי`,
    `להחמיץ`,
    `חדש`,
    `רגע`,
    `מוסלמי`,
    `מסגד`,
    `רוב`,
    `בעיקר`,
    `עכבר מחשב`,
    `לעבור`,
    `לעבור למקום/ממקום`,
    `רצח, לרצוח`,
    `שריר`,
    `מוזיקלי`,
    `מוזיקאי`,
    `עצמי`,
    `לכנות`,
    `אומה`,
    `לאום`,
    `טבעי`,
    `קרוב`,
    `ליד`,
    `הכרחי`,
    `שרשרת`,
    `גם לא, אף לא אחד`,
    `לא משנה`,
    `בדרך כלל`,
    `פתק`,
    `כלום`,
    `לשים לב`,
    `לוח מודעות`,
    `שם עצם`,
    `חפץ`,
    `מובן מאליו`,
    `כמובן`,
    `מובן שלא`,
    `להציע`,
    `קצין`,
    `הו`,
    `ישן`,
    `עולה באש`,
    `ברגל`,
    `למכירה`,
    `בזמן`,
    `מישהו`,
    `אחד את השני`,
    `יום אחד`,
    `לפתוח`,
    `להפעיל`,
    `דעה`,
    `הזדמנות`,
    `אפשרות`,
    `או משהו כזה`,
    `סדר`,
    `רגיל`,
    `ארגון`,
    `לארגן`,
    `מקורי`,
    `עצמנו`,
    `מקולקל`,
    `במשך`,
    `יותר`,
    `להיות חייב משהו למישהו`,
    `אחר הצהריים`,
    `חבילה`,
    `כאב`,
    `פיג'מה`,
    `ארמון`,
    `חבילה`,
    `חלק ממשהו`,
    `לחלוף`,
    `נוסע`,
    `דרכון`,
    `שביל`,
    `מטופל`,
    `דפוס`,
    `רוגע`,
    `אגס`,
    `פנסיה`,
    `פלפל`,
    `הופעה`,
    `תקופה`,
    `אישי`,
    `דלק`,
    `פיזי`,
    `פיזיקה`,
    `פסנתר`,
    `להרים, לקטוף`,
    `חתיכה`,
    `כרית`,
    `להתחרות`,
    `גן משחקים`,
    `לספק`,
    `מרוצה`,
    `סיפוק`,
    `שיר`,
    `נקודה`,
    `סיבה`,
    `מנומס`,
    `מסכן`,
    `פופקורן`,
    `עמדה`,
    `אפשרות`,
    `דואר, לשלוח`,
    `יכולת`,
    `חזק`,
    `הכנה`,
    `ללחוץ`,
    `כלא`,
    `אישי`,
    `להפיק`,
    `מקצועי`,
    `תוכנית`,
    `להבטיח, הבטחה`,
    `רכוש`,
    `הצעה`,
    `להגן`,
    `גאה`,
    `להוכיח`,
    `ציבורי`,
    `גור`,
    `טהור`,
    `סגול`,
    `כוונה`,
    `ארנק`,
    `לדחוף`,
    `להרתיע`,
    `לדחות`,
    `להדליק`,
    `ללבוש`,
    `להציע מישהו כמועמד`,
    `לכתוב`,
    `להרכיב`,
    `חידה`,
    `איכות`,
    `כמות`,
    `סימן שאלה`,
    `בשקט`,
    `למדי`,
    `תחרות`,
    `טווח`,
    `חולדה`,
    `להגיע`,
    `תגובה`,
    `להקריא`,
    `אמיתי`,
    `להבין`,
    `באמת`,
    `באמת`,
    `סביר`,
    `לקבל`,
    `אחרון, חדש`,
    `לזהות`,
    `להקליט, הקלטה`,
    `להוריד`,
    `להתייחס`,
    `קשרים`,
    `דת`,
    `להישאר`,
    `להסיר`,
    `לתקן, תיקון`,
    `לענות, תשובה`,
    `משאב`,
    `אחראי`,
    `עשיר`,
    `מיד`,
    `לצלצל, צליל`,
    `סלע`,
    `מוזיקת רוק`,
    `תפקיד`,
    `לגלגל, גלגול`,
    `עגול`,
    `תור`,
    `בטוח`,
    `מלוח`,
    `רוטב`,
    `נקניקייה`,
    `לשמור`,
    `צעיף`,
    `מדעי`,
    `מספריים`,
    `קורקינט`,
    `להבקיע, שער`,
    `לצרוח, צרחה`,
    `עונה`,
    `סוד`,
    `בסוד`,
    `נראה`,
    `לבחור`,
    `סלפי, דיוקן עצמי מצולם`,
    `חוש`,
    `נפרד`,
    `לשרת לקוח`,
    `להתכונן`,
    `מין, מיגדר`,
    `צללית`,
    `ללחוץ ידיים`,
    `צורה`,
    `חלק, לחלוק`,
    `סדין, דף`,
    `מדף`,
    `ספינה`,
    `לירות`,
    `קניות`,
    `לצעוק, צעקה`,
    `סגור`,
    `ביישן`,
    `צד`,
    `מראה`,
    `דממה`,
    `מטופש`,
    `כסף, כסוף`,
    `זהה`,
    `פשוט`,
    `יחיד`,
    `כיור`,
    `אדון`,
    `חדר אורחים`,
    `מצב`,
    `להחליק`,
    `סקי, לגלוש`,
    `שינה`,
    `חתיכה, לחתוך`,
    `רזה`,
    `חכם`,
    `ריח, להריח`,
    `לעשן`,
    `כך`,
    `עד כה`,
    `כדורגל`,
    `רך`,
    `משקה קל`,
    `תוכנה`,
    `חייל`,
    `איכשהו`,
    `סוג`,
    `חלל חיצון`,
    `דיבור`,
    `מקום`,
    `צוות`,
    `במה`,
    `תקן`,
    `כוכב, לככב`,
    `להביע`,
    `להמשיך, לשהות`,
    `קיטור`,
    `לצעוד`,
    `בטן`,
    `כאב בטן`,
    `אבן`,
    `לעצור`,
    `לחנות`,
    `חדשה`,
    `מייד`,
    `תות שדה`,
    `כוח`,
    `מאוד`,
    `חדר עבודה`,
    `סגנון`,
    `מקצוע לימודים`,
    `להצליח`,
    `כזה`,
    `כמו`,
    `להציע`,
    `להתאים`,
    `משקפי שמש`,
    `להניח`,
    `בוודאי`,
    `להפתיע`,
    `שחייה`,
    `בית כנסת`,
    `לבצע`,
    `לנוח`,
    `להיבחן`,
    `לקחת מישהו/משהו ברצינות`,
    `להתחרט`,
    `להוציא`,
    `טעם, לטעום`,
    `הוראה`,
    `צוות`,
    `דמעה`,
    `כפית`,
    `טכנולוגיה`,
    `בן נוער`,
    `לספר`,
    `להגיד למישהו לעשות משהו`,
    `לנטות לעשות`,
    `נוראי`,
    `חמור, מאוד`,
    `טקסט`,
    `תודות`,
    `הוא`,
    `ש...`,
    `זה בסדר`,
    `האוויר`,
    `הצבא`,
    `הכי טוב`,
    `מחרתיים`,
    `שלשום`,
    `הכלים`,
    `הראשון`,
    `העניין`,
    `הכי יפה/חשוב/פופולרי וכו'`,
    `אותו הדבר`,
    `הצעירים`,
    `תיאטרון`,
    `לשון רבים`,
    `עצמם`,
    `אז`,
    `לכן`,
    `אין ספק`,
    `עבה`,
    `לחשוב על משהו`,
    `לחשוב`,
    `למרות`,
    `מחשבה`,
    `איום`,
    `גרון`,
    `אגודל`,
    `רעם`,
    `לנקות`,
    `לקשור`,
    `קשר, עניבה`,
    `זמן`,
    `מערכת שעות`,
    `פחית`,
    `קטן`,
    `כותרת`,
    `עד`,
    `קלי, לקלות`,
    `היום`,
    `בוהן`,
    `יחד`,
    `לשון`,
    `חבל`,
    `כאב שיניים`,
    `משחת שיניים`,
    `הטוב ביותר, הבכיר`,
    `נושא`,
    `בסך הכול`,
    `לנגוע, מגע`,
    `סיור`,
    `לקראת`,
    `מגבת`,
    `מגדל`,
    `מסחר, לסחור`,
    `תנועה`,
    `להתאמן`,
    `רכבת חשמלית`,
    `נוסע`,
    `להתייחס`,
    `צרה`,
    `מכנסיים`,
    `משאית`,
    `אמון, לסמוך`,
    `לנסות`,
    `למדוד בגד`,
    `לעשות את המיטב`,
    `מנגינה`,
    `לדפדף`,
    `פינת רחוב`,
    `מכוער`,
    `הבנה`,
    `מדים`,
    `יחידה`,
    `אלא אם`,
    `לא הכרחי`,
    `לא נעים`,
    `עד`,
    `במעלה`,
    `שימוש`,
    `נהג לעשות/להיות`,
    `רגיל`,
    `וידאו`,
    `נגיף`,
    `לבקר`,
    `קול`,
    `קול`,
    `להצביע,  בחירה`,
    `חמים`,
    `להזהיר`,
    `להיזהר`,
    `לנופף`,
    `אנחנו`,
    `אתר אינטרנט`,
    `שבועי`,
    `משקל`,
    `היטב`,
    `עשוי היטב`,
    `רטוב`,
    `איך מישהו/משהו?`,
    `גלגל`,
    `בכל זמן ש...`,
    `אם`,
    `אם... או...`,
    `איזה`,
    `של מי`,
    `למה שלא?/למה שלא תעשה משהו?`,
    `למה לא?`,
    `במידה מרובה`,
    `פראי`,
    `בר`,
    `חלון`,
    `כנף`,
    `לאחל, משאלה`,
    `לתהות`,
    `צמר`,
    `לעבוד`,
    `לדאוג`,
    `גרוע`,
    `לשמוחלמשהו`,
    `לשמוח לעשות משהו`,
    `להעדיף`,
    `וואו!`,
    `לסיים`,
    `שגוי`,
    `אתה יודע`,
    `אחיך הגדול/אחותך הגדולה`,
    `עצמך`,
    `עצמכם`
]

export const hard = [
    `Entry`,
    `ability`,
    `absent`,
    `absolutely`,
    `abstract`,
    `academic`,
    `accept`,
    `accommodation`,
    `accurate`,
    `act`,
    `active`,
    `actual`,
    `adapt`,
    `add`,
    `adopt`,
    `against`,
    `agency`,
    `agree`,
    `ahead`,
    `aid`,
    `aim`,
    `aircraft`,
    `alcohol`,
    `alike`,
    `allow`,
    `alphabetical`,
    `alternative`,
    `ancient`,
    `angel`,
    `angry`,
    `ankle`,
    `anniversary`,
    `annual`,
    `any`,
    `anyhow`,
    `apart`,
    `apart from`,
    `appear`,
    `application`,
    `apply`,
    `appreciate`,
    `approach`,
    `approve`,
    `architect`,
    `area`,
    `argue`,
    `arrange`,
    `arrest`,
    `as`,
    `aspect`,
    `assess`,
    `assume`,
    `athlete`,
    `attach`,
    `attack`,
    `attempt`,
    `attend`,
    `attend`,
    `attract`,
    `authority`,
    `avatar`,
    `average`,
    `avoid`,
    `award`,
    `aware`,
    `awful`,
    `babysit`,
    `balance`,
    `bandage`,
    `barber`,
    `base`,
    `basic`,
    `basin`,
    `basis`,
    `battle`,
    `bean`,
    `bear`,
    `beat`,
    `bee`,
    `beef`,
    `before`,
    `belong`,
    `belt`,
    `beneath`,
    `benefit`,
    `beyond`,
    `bill`,
    `billion`,
    `bin`,
    `binge-watch`,
    `birth`,
    `bite`,
    `blame`,
    `blank`,
    `blind`,
    `block`,
    `blog`,
    `board`,
    `board`,
    `bomb`,
    `bone`,
    `bookcase`,
    `bother`,
    `bottom`,
    `breath`,
    `brief`,
    `broad`,
    `broadcast`,
    `brush`,
    `budget`,
    `builder`,
    `burger`,
    `burn`,
    `business`,
    `butterfly`,
    `button`,
    `by`,
    `cabbage`,
    `cage`,
    `camp`,
    `can`,
    `canal`,
    `cancel`,
    `candidate`,
    `capable`,
    `captain`,
    `care`,
    `career`,
    `carpet`,
    `carry`,
    `cartoon`,
    `case`,
    `cast`,
    `category`,
    `cause`,
    `celebrity`,
    `central`,
    `certain`,
    `certainty`,
    `chain`,
    `challenge`,
    `chance`,
    `change`,
    `chapter`,
    `character`,
    `charity`,
    `chart`,
    `cheek`,
    `cheerful`,
    `chemistry`,
    `chest`,
    `chewing gum`,
    `chief`,
    `chin`,
    `choice`,
    `circular`,
    `circumstance`,
    `citizen`,
    `class`,
    `clear`,
    `client`,
    `climate`,
    `close`,
    `coast`,
    `code`,
    `colleague`,
    `collect`,
    `college`,
    `column`,
    `combined`,
    `comedy`,
    `comment`,
    `commit`,
    `commitment`,
    `committee`,
    `common sense`,
    `common`,
    `communicate`,
    `community`,
    `complain`,
    `complete`,
    `complex`,
    `concentrate`,
    `concern`,
    `conclusion`,
    `conference`,
    `confidence`,
    `confirm`,
    `conflict`,
    `confusion`,
    `consciousness`,
    `consider`,
    `constant`,
    `construction`,
    `content`,
    `contrast`,
    `contribute`,
    `convenient`,
    `convert`,
    `cool`,
    `cottage`,
    `could`,
    `council`,
    `count`,
    `county`,
    `couple`,
    `course`,
    `court`,
    `creature`,
    `crew`,
    `crime`,
    `crisis`,
    `crowd`,
    `crown`,
    `crucial`,
    `cruel`,
    `cucumber`,
    `culture`,
    `curious`,
    `curly`,
    `currency`,
    `curriculum`,
    `custom`,
    `cut`,
    `damage`,
    `damn`,
    `dark`,
    `data`,
    `debate`,
    `defend`,
    `define`,
    `definite`,
    `degree`,
    `delete`,
    `delicious`,
    `democracy`,
    `demonstrate`,
    `deny`,
    `depression`,
    `design`,
    `desire`,
    `desktop`,
    `despite`,
    `detail`,
    `detective`,
    `device`,
    `dialog/dialogue`,
    `diet`,
    `direct`,
    `director`,
    `disadvantage`,
    `disagree`,
    `disappoint`,
    `dish`,
    `display`,
    `district`,
    `dive`,
    `divide`,
    `documentary`,
    `dolphin`,
    `domestic`,
    `dot`,
    `download`,
    `downtown`,
    `drama`,
    `dream`,
    `dressed`,
    `driving license`,
    `drug`,
    `drug`,
    `due to`,
    `dust`,
    `duty`,
    `duty-free`,
    `eastern`,
    `economy`,
    `edge`,
    `effective`,
    `either … or`,
    `electric`,
    `electronic`,
    `elementary`,
    `emergency`,
    `employment`,
    `encourage`,
    `endless`,
    `engineer`,
    `enormous`,
    `ensure`,
    `entertain`,
    `entire`,
    `equal`,
    `escape`,
    `essential`,
    `establish`,
    `estimate`,
    `etc.`,
    `even`,
    `eventually`,
    `ever since`,
    `evidence`,
    `examine`,
    `exchange`,
    `excitement`,
    `excuse`,
    `exhibition`,
    `expectation`,
    `experience`,
    `experiment`,
    `expert`,
    `expression`,
    `extent`,
    `external`,
    `extra`,
    `face-to-face`,
    `facilities`,
    `facility`,
    `factor`,
    `fail`,
    `fair`,
    `faith`,
    `fall`,
    `fall`,
    `fault`,
    `favor`,
    `fee`,
    `feel`,
    `female`,
    `festival`,
    `fever`,
    `few`,
    `fiction`,
    `fight`,
    `figure`,
    `file`,
    `finally`,
    `finish`,
    `fire`,
    `fire station`,
    `firefighter`,
    `flavor`,
    `flow`,
    `follower`,
    `following`,
    `for`,
    `force`,
    `foreign`,
    `forever`,
    `forgive`,
    `form`,
    `fortunately`,
    `frame`,
    `freeze`,
    `frequently`,
    `from`,
    `fry`,
    `fuel`,
    `full-time`,
    `funny`,
    `future`,
    `future`,
    `gallery`,
    `garage`,
    `gather`,
    `gay`,
    `general`,
    `gentle`,
    `global`,
    `goal`,
    `goods`,
    `grade`,
    `grant`,
    `green`,
    `greet`,
    `grounds`,
    `grow`,
    `guess`,
    `guilty`,
    `haircut`,
    `handle`,
    `handsome`,
    `happiness`,
    `headline`,
    `heat`,
    `high`,
    `high-tech/hi-tech`,
    `hire`,
    `hire`,
    `historical`,
    `hit`,
    `Holocaust / the Holocaust`,
    `honest`,
    `honor`,
    `hot`,
    `household`,
    `housework`,
    `human`,
    `humor`,
    `hurt`,
    `identity`,
    `if`,
    `illegal`,
    `imagination`,
    `income`,
    `incorrect`,
    `indeed`,
    `independence`,
    `individual`,
    `influence`,
    `injure`,
    `inner`,
    `insist`,
    `institution`,
    `intend`,
    `interested`,
    `internal`,
    `interview`,
    `into`,
    `introduction`,
    `introduction`,
    `iron`,
    `It seems …`,
    `jar`,
    `jet`,
    `join`,
    `judge`,
    `jungle`,
    `key`,
    `killed`,
    `kind`,
    `knock`,
    `Koran`,
    `lab`,
    `label`,
    `labor`,
    `ladder`,
    `lady`,
    `last`,
    `lately`,
    `later`,
    `later on`,
    `law`,
    `lead`,
    `league`,
    `leave`,
    `legal`,
    `leisure`,
    `length`,
    `let me/us`,
    `lie`,
    `life`,
    `lift`,
    `likes and dislikes`,
    `link`,
    `lioness`,
    `literature`,
    `live`,
    `loads of/a load of`,
    `loss`,
    `low`,
    `mad`,
    `major`,
    `majority`,
    `make`,
    `make-up`,
    `male`,
    `mall`,
    `manage`,
    `marathon`,
    `master`,
    `match`,
    `material`,
    `mathematics`,
    `matter`,
    `mean`,
    `mean`,
    `meanwhile`,
    `metal`,
    `method`,
    `meter`,
    `might`,
    `mile`,
    `mind`,
    `mind`,
    `minister`,
    `minor`,
    `miss`,
    `missing`,
    `mix`,
    `model`,
    `model`,
    `motor`,
    `myth`,
    `near`,
    `negative`,
    `neighborhood`,
    `network`,
    `next`,
    `no longer`,
    `no way`,
    `nor`,
    `northern`,
    `not even`,
    `not really`,
    `novel`,
    `now`,
    `nowadays`,
    `nowhere`,
    `nuclear`,
    `obey`,
    `occasion`,
    `occur`,
    `ocean`,
    `odd`,
    `of`,
    `officer`,
    `omelette/omelet`,
    `on purpose`,
    `on the way to/from`,
    `once again/once more`,
    `one`,
    `one day / some day / one of these days`,
    `onto/on to`,
    `open`,
    `opera`,
    `oppose`,
    `opposite`,
    `or`,
    `or not`,
    `order`,
    `order`,
    `original`,
    `originally`,
    `ought to`,
    `out`,
    `out loud`,
    `out of`,
    `out of work`,
    `outdoors`,
    `out-of-date/out of date`,
    `oven`,
    `over`,
    `over here/over there`,
    `own`,
    `pan`,
    `pants`,
    `paragraph`,
    `park`,
    `parliament`,
    `partner`,
    `party`,
    `pass`,
    `password`,
    `pay`,
    `pepper`,
    `per`,
    `percent/per cent`,
    `perfectly`,
    `perform`,
    `period`,
    `permanent`,
    `permit`,
    `persuade`,
    `photocopy`,
    `photographer`,
    `phrase`,
    `pie`,
    `pile`,
    `pipe`,
    `place`,
    `plain`,
    `plan`,
    `play`,
    `plenty`,
    `plural`,
    `poet`,
    `point`,
    `point`,
    `politics`,
    `poor`,
    `pop`,
    `port`,
    `positive`,
    `possibly`,
    `post`,
    `postpone`,
    `pot`,
    `power`,
    `power`,
    `practical`,
    `presence`,
    `pretty`,
    `previous`,
    `prince`,
    `print`,
    `process`,
    `profit`,
    `program`,
    `progress`,
    `pronounce`,
    `proper`,
    `property`,
    `provide`,
    `public`,
    `publish`,
    `quite a bit`,
    `quite a few/a lot`,
    `quite a while`,
    `raise`,
    `rare`,
    `rate`,
    `rate`,
    `rather`,
    `rather than`,
    `real`,
    `reality`,
    `receipt`,
    `reception`,
    `recipe`,
    `record`,
    `recover`,
    `refuse`,
    `regular`,
    `relative`,
    `relatively good / bad / cheap, etc.`,
    `release`,
    `report`,
    `represent`,
    `require`,
    `respond`,
    `result in sth`,
    `reward`,
    `ride`,
    `right`,
    `rise`,
    `roast`,
    `roll`,
    `root`,
    `rose`,
    `rough`,
    `route`,
    `royal`,
    `rubber`,
    `safety`,
    `sail`,
    `sale`,
    `sand`,
    `save`,
    `savings`,
    `say`,
    `scene`,
    `search`,
    `second`,
    `section`,
    `security`,
    `see`,
    `seed`,
    `seek`,
    `seems like/as if/t`,
    `self-service`,
    `series`,
    `serious`,
    `session`,
    `sew`,
    `shake`,
    `shall`,
    `sharp`,
    `shine`,
    `shock`,
    `shoot`,
    `shop`,
    `shop assistant`,
    `shortly afterward; shortly after / before sth`,
    `show`,
    `shower`,
    `sign`,
    `simply`,
    `since`,
    `single`,
    `single parent`,
    `singular`,
    `site`,
    `skill`,
    `skin`,
    `so`,
    `so (that)`,
    `social media`,
    `social networking`,
    `society`,
    `soft`,
    `solid`,
    `solve`,
    `somewhat`,
    `sorry`,
    `soul`,
    `source`,
    `southern`,
    `spare`,
    `sparkling water/wine`,
    `speak`,
    `spice`,
    `stadium`,
    `stage`,
    `standard`,
    `state`,
    `state`,
    `station`,
    `statue`,
    `step`,
    `stick`,
    `stir`,
    `store`,
    `stranger`,
    `strategy`,
    `stress`,
    `stress`,
    `strike`,
    `strong`,
    `studio`,
    `stuff`,
    `stupid`,
    `subject`,
    `success`,
    `such`,
    `sudden`,
    `suffer`,
    `suitable`,
    `sum`,
    `sunrise`,
    `sunset`,
    `sunshine`,
    `supply`,
    `support`,
    `surround`,
    `swallow`,
    `switch`,
    `sympathy`,
    `system`,
    `tablespoon`,
    `tag`,
    `talent`,
    `talk`,
    `target`,
    `task`,
    `tax`,
    `technical`,
    `technique`,
    `telecommunications`,
    `temperature`,
    `temperature`,
    `temporary`,
    `tense`,
    `tent`,
    `term`,
    `terrific`,
    `test`,
    `the`,
    `the law`,
    `the other day/week etc.`,
    `the press`,
    `the public`,
    `the same thing`,
    `the sights`,
    `the West`,
    `then`,
    `these days`,
    `they`,
    `things`,
    `things like that`,
    `think`,
    `thirst`,
    `though`,
    `thread`,
    `through`,
    `time`,
    `tip`,
    `tire/tyre`,
    `tissue`,
    `to`,
    `tone`,
    `tool`,
    `total`,
    `tour`,
    `track`,
    `tradition`,
    `translate`,
    `treat`,
    `trend`,
    `trial`,
    `truth`,
    `tunnel`,
    `turkey`,
    `tweet`,
    `type`,
    `typical`,
    `under`,
    `underground`,
    `underline`,
    `unfriendly`,
    `unimportant`,
    `unkind`,
    `up`,
    `update`,
    `upper`,
    `upset`,
    `upside down`,
    `up-to-date/up to date`,
    `use`,
    `useless`,
    `user-friendly`,
    `valley`,
    `value`,
    `various`,
    `vegetarian`,
    `vehicle`,
    `victory`,
    `violence`,
    `viral`,
    `virtual`,
    `vision`,
    `volunteer`,
    `wallet`,
    `waste`,
    `weak`,
    `wedding`,
    `well-known`,
    `western`,
    `What about ...?`,
    `What if …?`,
    `What's up`,
    `which`,
    `who`,
    `whoever`,
    `win`,
    `wipe`,
    `wish sb luck`,
    `wonder`,
    `wood`,
    `work`,
    `work`,
    `would`,
    `would rather`,
    `Would you mind ...?`,
    `wrap`,
    `write`,
    `written`,
    `yet`,
    `youth`,
    `zone`
]

export const hard_hebrew = [
    `Translation`,
    `יְכוֹלֶת`,
    `נֶעדָר`,
    `לחלוטין`,
    `תַקצִיר, מופשט`,
    `אקדמי`,
    `להסכים`,
    `דִיוּר`,
    `מְדוּיָק`,
    `פעולה, לבצע`,
    `פָּעִיל`,
    `מַמָשִׁי`,
    `לְהִסְתָגֵל`,
    `לְהוֹסִיף`,
    `לְאַמֵץ`,
    `מול`,
    `סוֹכְנוּת`,
    `לְהַסכִּים`,
    `קָדִימָה`,
    `סיוע`,
    `לכוון, מַטָרָה`,
    `כְּלִי טַיִס`,
    `כּוֹהֶל`,
    `דוֹמֶה`,
    `להתיר`,
    `אָלֶף בֵּיתִי`,
    `חֲלוּפָה`,
    `עָתִיק`,
    `מַלְאָך`,
    `כּוֹעֵס`,
    `קרסול`,
    `יוֹם הַשָׁנָה`,
    `שנתי`,
    `כל, שום דבר`,
    `עַל כֹּל פָּנִים`,
    `מלבד`,
    `חוץ מ`,
    `לְהוֹפִיעַ`,
    `יישומון`,
    `לבקש, בקשה`,
    `מעריך`,
    `לגשת, גִישָׁה`,
    `לְאַשֵׁר`,
    `אַדְרִיכָל`,
    `תחום`,
    `לא להסכים`,
    `לְאַרגֵן`,
    `לעצור, מַעְצָר`,
    `מאחר ש`,
    `היבט`,
    `לְהַעֲרִיך`,
    `לְהַנִיחַ`,
    `אַתלֵט`,
    `לְצַרֵף`,
    `לִתְקוֹף, תקיפה`,
    `ניסיון, לְנַסוֹת`,
    `לבקר במקום באופן קבוע`,
    `להשתתף`,
    `לִמְשׁוֹך`,
    `רָשׁוּת`,
    `גִלגוּל`,
    `מְמוּצָע`,
    `לְהִמָנַע`,
    `פרס, להעניק פרס`,
    `מוּדָע`,
    `נורא`,
    `לִשְׁמוֹר עַל הַטַף`,
    `איזון, לאזן`,
    `תַחְבּוֹשֶׁת`,
    `סַפָּר`,
    `תחתית`,
    `בסיסי`,
    `אַגָן`,
    `בָּסִיס`,
    `מאבק`,
    `אפונה`,
    `לשאת בעול`,
    `להביס`,
    `דבורה`,
    `בשר בקר`,
    `לפני`,
    `להשתייך`,
    `חֲגוֹרָה`,
    `תַחַת`,
    `תועלת, להפיק תועלת`,
    `מעבר`,
    `קבלה`,
    `מיליארד`,
    `פַּח`,
    `צפיית רצף`,
    `הוּלֶדֶת`,
    `לנגוס, לעקוץ, נגיסה, עקיצה`,
    `להאשים`,
    `רֵיק`,
    `עיוור`,
    `גוש`,
    `יוֹומן רשת`,
    `לעלות על ספינה, רכבת, מטוס`,
    `משטח`,
    `פְּצָצָה, לפוצץ`,
    `עֶצֶם`,
    `כּוֹנָנִית`,
    `לְהטרִיד`,
    `ישבן`,
    `נְשִׁימָה`,
    `קָצָר`,
    `רָחָב`,
    `לשדר, מִשׁדָר`,
    `מִברֶשֶׁת, להבריש`,
    `תַקצִיב`,
    `בנאי`,
    `המבורגר`,
    `להישרף`,
    `עֵסֶק`,
    `פַּרְפַּר`,
    `לַחְצָן`,
    `ליד`,
    `כרוב`,
    `כְּלוּב`,
    `להקים מחנה`,
    `להיות יכול`,
    `תְעָלָה`,
    `לְבַטֵל`,
    `מוּעֲמָד`,
    `בעל יכולת`,
    `סֶרֶן`,
    `לדאוג`,
    `קריירה`,
    `שָׁטִיחַ`,
    `לשאת`,
    `קָרִיקָטוּרָה`,
    `מקרה`,
    `השלכה`,
    `קטגוריה`,
    `גורם, לגרום`,
    `סלבריטאי`,
    `מֶרכָּזִי`,
    `מסוים`,
    `וַדָאוּת`,
    `שַׁרשֶׁרֶת`,
    `אתגר, לאתגר`,
    `סיכוי`,
    `להמיר כסף`,
    `פֶּרֶק`,
    `דמות`,
    `צדקה`,
    `תרשים`,
    `לֶחִי`,
    `עַלִיז`,
    `כִּימִיָה`,
    `חזה`,
    `מסטיק`,
    `רֹאשׁ`,
    `סַנְטֵר`,
    `מבחר`,
    `עָגוֹל`,
    `נסיבות`,
    `אֶזרָח`,
    `מעמד`,
    `לפנות, פנוי`,
    `לקוח`,
    `אַקלִים`,
    `סגור`,
    `חוף`,
    `תקנון`,
    `שותף לעבודה`,
    `לאסוף`,
    `מִכלָלָה`,
    `עמוד בבניין`,
    `מְשׁוּלָב`,
    `קוֹמֶדִיָה`,
    `תגובה, להגיב`,
    `להתחייב`,
    `מְחוּיָבוּת`,
    `וַעֲדָה`,
    `שכל ישר`,
    `נפוץ`,
    `לתקשר`,
    `קהילה`,
    `לְהִתְלוֹנֵן`,
    `לְהַשְׁלִים`,
    `מורכב`,
    `לְהִתְרַכֵּז`,
    `דְאָגָה`,
    `סיכום`,
    `וְעִידָה`,
    `אֵמוּן`,
    `לְאַשֵׁר`,
    `סְתִירָה`,
    `בִּלבּוּל`,
    `תוֹדָעָה`,
    `לשקול`,
    `קָבוּעַ`,
    `בְּנִיָה`,
    `תוֹכֶן`,
    `ניגוד`,
    `לתרום`,
    `נוֹחַ`,
    `להמיר`,
    `לצנן`,
    `בקתה`,
    `הָיָה יָכוֹל`,
    `מועצה`,
    `לספור`,
    `מָחוֹז`,
    `זוּג`,
    `מנה`,
    `בית משפט`,
    `יְצוּר`,
    `צוות`,
    `פֶּשַׁע`,
    `מַשׁבֵּר`,
    `קָהָל`,
    `כֶּתֶר`,
    `מַכרִיעַ`,
    `אַכְזָרִי`,
    `מלפפון`,
    `תַרְבּוּת`,
    `סקרן`,
    `מְתוּלתָל`,
    `מַטְבֵּעַ`,
    `תוכנית הלימודים`,
    `מותאם אישית`,
    `חתך, שריטה`,
    `נֵזֶק, לגרום נזק`,
    `לעזאזל`,
    `אפל`,
    `נתונים`,
    `עימות, להתעמת`,
    `לְהַגֵן`,
    `לְהַגדִיר`,
    `מוּגדָר`,
    `כמות`,
    `לִמְחוֹק`,
    `טָעִים מְאוֹד`,
    `דֵמוֹקרָטִיָה`,
    `להוכיח`,
    `לְהַכּחִישׁ`,
    `דִכָּאוֹן`,
    `עיצוב, לְעַצֵב`,
    `רצון עז`,
    `שולחן העבודה`,
    `למרות`,
    `פרט`,
    `בַּלָשׁ`,
    `התקן`,
    `דיאלוג`,
    `דִיאֵטָה, לשמור על דיאטה`,
    `ישיר`,
    `מְנַהֵל`,
    `חִסָרוֹן`,
    `לא להסכים`,
    `לְאַכזֵב`,
    `מאכל`,
    `לְהַצִיג, תצוגה`,
    `מָחוֹז`,
    `לִצְלוֹל`,
    `לחלק`,
    `תיעודי`,
    `דולפין`,
    `בֵּיתִי`,
    `נְקוּדָה`,
    `להוריד, הורדה (ממחשב, מהאינטרנט)`,
    `מרכז העיר`,
    `דְרָמָה`,
    `חלום, לחלום`,
    `לָבוּשׁ`,
    `רשיון נהיגה`,
    `סם`,
    `תְרוּפָה`,
    `עקב`,
    `אָבָק, לאבק`,
    `חוֹבָה`,
    `פטור ממכס`,
    `מזרחי`,
    `כַּלְכָּלָה`,
    `קָצֶה`,
    `יָעִיל`,
    `או … או`,
    `חשמלי`,
    `אֶלֶקטרוֹנִי`,
    `יְסוֹדִי`,
    `חרום`,
    `תעסוקה`,
    `לְעוֹדֵד`,
    `אינסופי`,
    `מהנדס`,
    `עֲנָקִי`,
    `לְהַבטִיחַ`,
    `לְבַדֵר`,
    `שלם`,
    `שווה`,
    `לברוח`,
    `חִיוּנִי`,
    `לְהַקִים`,
    `לְהַעֲרִיך`,
    `וכו'`,
    `אֲפִילוּ`,
    `בסופו של דבר`,
    `מאז ש`,
    `עֵדוּת`,
    `לִבחוֹן`,
    `החלפה`,
    `התרגשות`,
    `תירוץ`,
    `תערוכה`,
    `ציפייה`,
    `ניסיון, להתנסות`,
    `ניסוי, לְנַסוֹת`,
    `מוּמחֶה`,
    `הבעה`,
    `היקף`,
    `חיצוני`,
    `תוֹסֶפֶת`,
    `פנים אל פנים`,
    `מתקנים`,
    `מִתקָן`,
    `גורם`,
    `לְהִכָּשֵׁל`,
    `יריד`,
    `אֱמוּנָה`,
    `נפילה`,
    `ירידה`,
    `אשמה`,
    `טוֹבָה`,
    `תַשְׁלוּם`,
    `להרגיש`,
    `נְקֵבָה`,
    `פֶסטִיבָל`,
    `חום`,
    `מְעַטִים`,
    `ספרות בדיונית`,
    `להיאבק, מַאֲבָק`,
    `מספר`,
    `קוֹבֶץ`,
    `סוף כל סוף`,
    `סוף`,
    `לירות`,
    `תחנת כיבוי אש`,
    `כבאי`,
    `טעם`,
    `לזרום, זְרִימָה`,
    `חָסִיד, עוקב`,
    `הבא`,
    `ל`,
    `כּוֹחַ`,
    `זָר`,
    `לָנֶצַח`,
    `לִסְלוֹחַ`,
    `ליצור`,
    `לְמַרְבֶּה הַמַזָל`,
    `מִסגֶרֶת`,
    `להקפיא`,
    `בתדירות גבוהה`,
    `מ`,
    `לטגן`,
    `דלק`,
    `במשרה מלאה`,
    `מצחיק`,
    `עתיד`,
    `עתידי`,
    `גלריה`,
    `מוּסָך`,
    `לאסוף`,
    `שמח`,
    `כללי`,
    `עָדִין`,
    `גלוֹבָּלִי`,
    `מטרה`,
    `סְחוֹרוֹת`,
    `ציון, לדרג`,
    `להעניק, מענק`,
    `ידידותי לסביבה`,
    `לברך`,
    `עילה`,
    `לגדול`,
    `ניחוש`,
    `אָשֵׁם`,
    `תִספּוֹרֶת`,
    `להתמודד`,
    `נאה`,
    `אושר`,
    `כּוֹתֶרֶת`,
    `חוֹם`,
    `גָבוֹהַ`,
    `הייטק`,
    `להעסיק`,
    `לִשְׂכּוֹר`,
    `הִיסטוֹרִי`,
    `להיט`,
    `שואה`,
    `יָשָׁר`,
    `כָּבוֹד`,
    `חריף`,
    `בית`,
    `עבודות בית`,
    `בן אנוש`,
    `הוּמוֹר`,
    `לכאוב`,
    `זהות`,
    `אם`,
    `בִּלתִי חוּקִי`,
    `דִמיוֹן`,
    `הַכנָסָה`,
    `לֹא נָכוֹן`,
    `אכן`,
    `עצמאות`,
    `אִישִׁי`,
    `לְהַשְׁפִּיעַ, השפעה`,
    `לִפְגוֹעַ`,
    `פְּנִימִי`,
    `להתעקש`,
    `מוֹסָד`,
    `להתכוון`,
    `מעוניין`,
    `פְּנִימִי`,
    `רֵאָיוֹן`,
    `לְתוֹך`,
    `מבוא`,
    `הצגה של מישהו בפני מישהו`,
    `בַּרזֶל`,
    `נראה ש …`,
    `קַנקַן`,
    `מטוס סילון`,
    `לְהִצְטַרֵף`,
    `לִשְׁפּוֹט`,
    `ג'וּנגֶל`,
    `מַפְתֵחַ`,
    `נהרג`,
    `סוג`,
    `לנקוש, נְקִישָׁה`,
    `קוּרָאן`,
    `מַעבָּדָה`,
    `תווית`,
    `עבודה`,
    `סוּלָם`,
    `גברת`,
    `להימשך`,
    `לָאַחֲרוֹנָה`,
    `מאוחר יותר`,
    `בהמשך`,
    `משפטים`,
    `להוביל`,
    `לִיגָה`,
    `לעזוב`,
    `משפטי`,
    `פְּנַאִי`,
    `אורך`,
    `הנח לי/לנו לעשות משהו`,
    `לשקר`,
    `חַיִים`,
    `מעלית`,
    `דברים אהובים ושנואים`,
    `לקשר, קישור`,
    `לְבִיאָה`,
    `סִפְרוּת`,
    `בשידור חי`,
    `המון/עומס של`,
    `הֶפסֵד`,
    `נָמוּך`,
    `מְטוּרָף`,
    `גדול`,
    `רוֹב`,
    `לעשות`,
    `איפור`,
    `זָכָר`,
    `קניוֹן`,
    `לנהל`,
    `מָרָתוֹן`,
    `שליט`,
    `תחרות ספורט`,
    `אריג`,
    `מָתֵימָטִיקָה`,
    `להיות משמעותי`,
    `מרושע`,
    `להתכוון`,
    `בינתיים`,
    `מַתֶכֶת`,
    `שיטה`,
    `מטר`,
    `להיות עלול`,
    `מייל (יחידת אורך)`,
    `להיות מוטרד`,
    `להיזהר`,
    `שר בממשלה`,
    `קַטִין`,
    `להתגעגע`,
    `חָסֵר`,
    `שילוב`,
    `דוגמן/ית`,
    `דֶגֶם`,
    `מָנוֹעַ`,
    `מִיתוֹס`,
    `סמוך לזמן`,
    `שלילי`,
    `שְׁכוּנָה`,
    `רֶשֶׁת`,
    `הַבָּא`,
    `כבר לא`,
    `אין סיכוי`,
    `ולא`,
    `צְפוֹנִי`,
    `אפילו לא`,
    `לא באמת`,
    `רוֹמָן`,
    `עַכשָׁיו`,
    `כַּיוֹם`,
    `לְשׁוּם מָקוֹם`,
    `גַרעִינִי`,
    `לציית`,
    `הִזדַמְנוּת`,
    `להתרחש`,
    `אוקיינוס`,
    `מוזר`,
    `שֶׁל`,
    `קָצִין`,
    `חביתה`,
    `בכוונה`,
    `בדרך אל/מ`,
    `פעם נוספת/עוד פעם`,
    `אחד`,
    `יום אחד / ביום מן הימים`,
    `על`,
    `פתוח`,
    `אוֹפֵּרָה`,
    `לְהִתְנַגֵד`,
    `הפוך`,
    `פן`,
    `או שלא`,
    `לפקוד, פקודה`,
    `סדר`,
    `מְקוֹרִי`,
    `בְּמָקוֹר`,
    `צריך`,
    `הַחוּצָה`,
    `בקול`,
    `מִתוֹך`,
    `להיות מובטל`,
    `מחוץ לבית`,
    `לא מעודכן`,
    `תנור`,
    `גמור`,
    `כאן/שם`,
    `להיות בעלים`,
    `מחבת`,
    `מִכְנָסַיִים`,
    `פסקה`,
    `לחנות`,
    `פַּרלָמֶנט`,
    `בן/בת זוג`,
    `מפלגה`,
    `לַעֲבוֹר`,
    `סיסמה`,
    `משכורת`,
    `פלפל`,
    `לְכָל`,
    `אחוז`,
    `בצורה מושלמת`,
    `להופיע`,
    `נקודה בסוף משפט`,
    `קבוע`,
    `לְהַתִיר`,
    `לְשַׁכְנֵעַ`,
    `העתק`,
    `צַלָם`,
    `מִשׁפָּט`,
    `פַּאִי`,
    `עֲרֵמָה`,
    `צינור`,
    `מקום`,
    `פשוט`,
    `תוכנית`,
    `משחק, לְשַׂחֵק`,
    `שפע`,
    `רַבִּים`,
    `משורר/ת`,
    `נְקוּדָה`,
    `נְקוּדָה במשחק`,
    `פּוֹלִיטִיקָה`,
    `עני`,
    `פּוֹפּ`,
    `נמל`,
    `חִיוּבִי`,
    `יִתָכֵן`,
    `לפרסם, פרסום באינטרנט`,
    `לִדחוֹת`,
    `סיר`,
    `כּוֹחַ`,
    `חשמל`,
    `מַעֲשִׂי`,
    `נוכחות`,
    `למדי`,
    `קודם`,
    `נסיך`,
    `להדפיס, הדפס`,
    `תהליך`,
    `רווח`,
    `תוכנה, לתכנת`,
    `התקדמות`,
    `לְבַטֵא`,
    `תָקִין`,
    `נכס`,
    `לְסַפֵּק`,
    `פּוּמְבֵּי`,
    `לְפַרְסֵם`,
    `לא מעט`,
    `לא מעט/הרבה`,
    `זמן ממושך`,
    `להעלות`,
    `נָדִיר`,
    `קצב`,
    `תעריף`,
    `במידת מה`,
    `ולא`,
    `אמיתי`,
    `מְצִיאוּת`,
    `קַבָּלָה`,
    `דלפק קבלה`,
    `מתכון`,
    `שיא`,
    `לְהַחלִים`,
    `לסרב`,
    `קבוע, חוזר על עצמו`,
    `קרוב משפחה`,
    `יחסית טוב / רע / זול וכו'.`,
    `לְשַׁחְרֵר, שחרור`,
    `דו"ח, דיווח`,
    `לְיַצֵג`,
    `לִדרוֹשׁ`,
    `לְהָגִיב`,
    `לנבוע ממשהו`,
    `פרס`,
    `לנסוע`,
    `נכון`,
    `לעלות, עלייה`,
    `לצלות, צלוי`,
    `גָלִיל`,
    `שורש`,
    `ורד`,
    `מְחוּספָּס`,
    `מַסלוּל`,
    `מלכותי`,
    `מחק`,
    `בְּטִיחוּת`,
    `לשוט`,
    `מְכִירָה`,
    `חוֹל`,
    `להגן`,
    `חיסכון`,
    `לומר`,
    `נוף`,
    `חיפוש, לחפש`,
    `שני/יה`,
    `סָעִיף`,
    `בִּטָחוֹן`,
    `להבין`,
    `זֶרַע`,
    `לְחַפֵּשׂ`,
    `נראה כמו/כאילו/ל`,
    `שירות עצמי`,
    `סִדרָה`,
    `רְצִינִי`,
    `מוֹשָׁב`,
    `לִתְפוֹר`,
    `לְנַעֵר`,
    `לעשות משהו`,
    `חַד`,
    `לזהור`,
    `הֶלֶם, להמם`,
    `לקלוע למטרה`,
    `לִקְנוֹת`,
    `עוזר בחנות`,
    `זמן קצר לאחר מכן; זמן קצר אחרי/לפני משהו`,
    `להראות`,
    `גשם קל`,
    `סִימָן`,
    `בפשטות`,
    `מאחר ש...`,
    `רווק/ה`,
    `הורה יחיד`,
    `יָחִיד`,
    `אֲתַר`,
    `מְיוּמָנוּת`,
    `עור, קליפה`,
    `כך`,
    `אז`,
    `מדיה חברתית`,
    `רשת חברתית`,
    `חֶברָה`,
    `רַך`,
    `מוצק`,
    `לִפְתוֹר`,
    `במידה מסוימת`,
    `לא, תודה`,
    `נֶפֶשׁ`,
    `מָקוֹר`,
    `דְרוֹמִי`,
    `נוֹסָף`,
    `מים מוגזים/יין`,
    `לְדַבֵּר`,
    `תבלין`,
    `אִצטַדיוֹן`,
    `שלב`,
    `תֶקֶן`,
    `מצב`,
    `מדינה, מדיני`,
    `תַחֲנָת שידור`,
    `פסל`,
    `שלב`,
    `להדביק`,
    `לערבב`,
    `לאחסן`,
    `זָר`,
    `אִסטרָטֶגִיָה`,
    `להדגיש, דגש`,
    `לחץ`,
    `לְהַכּוֹת`,
    `חָזָק`,
    `סטוּדִיוֹ`,
    `דברים`,
    `מְטוּפָּשׁ`,
    `נושא`,
    `הַצלָחָה`,
    `כגון`,
    `פִּתְאוֹמִי`,
    `לסבול`,
    `מַתְאִים`,
    `סְכוּם`,
    `זריחת השמש`,
    `שקיעת השמש`,
    `אוֹר שֶׁמֶשׁ`,
    `הצע, לְסַפֵּק`,
    `לתמוך, תמיכה`,
    `לְהַקִיף`,
    `לִבלוֹעַ`,
    `להחליף`,
    `אַהֲדָה`,
    `מערכת`,
    `כַּף`,
    `תיוג`,
    `כִּשָׁרוֹן`,
    `שיחה`,
    `יַעַד`,
    `מטלה`,
    `מַס`,
    `טֶכנִי`,
    `טֶכנִיקָה`,
    `תקשורת`,
    `חום גוף`,
    `חוֹם`,
    `זמני`,
    `זמן דקדוקי`,
    `אוֹהֶל`,
    `מושג`,
    `מְצוּיָן`,
    `מִבְחָן, לבחון`,
    `ה' (תווית יידוע)`,
    `החוק`,
    `אתמול/השבוע שעבר וכו'`,
    `העיתונות`,
    `הציבור`,
    `אותו הדבר`,
    `המראות`,
    `המערב`,
    `נוסף על כך`,
    `כיום`,
    `הם/הן`,
    `חפצים, דברים`,
    `דברים כאלה`,
    `לזכור`,
    `צָמָא`,
    `אמנם`,
    `פְּתִיל`,
    `באמצעות`,
    `אירוע, תקופה`,
    `תשר`,
    `צמיג`,
    `רִקמָה`,
    `ל`,
    `טוֹן`,
    `כְּלִי`,
    `סכום`,
    `לסייר`,
    `מַסלוּל`,
    `מָסוֹרֶת`,
    `לתרגם`,
    `לטפל`,
    `מְגַמָה`,
    `משפט`,
    `אֶמֶת`,
    `מִנהָרָה`,
    `תרנגול הודו`,
    `צִיוּץ`,
    `להקליד`,
    `טיפוסי`,
    `פחות מ`,
    `תת קרקעי`,
    `לשרטט קו תחתון`,
    `לֹא יְדִידוּתִי`,
    `לֹא חָשׁוּב`,
    `לא נדיב`,
    `לְמַעלָה`,
    `לעדכן, עדכון`,
    `עֶלִיוֹן`,
    `לעצבן, עצבני`,
    `הפוך`,
    `עדכני`,
    `להשתמש, שימוש`,
    `חֲסַר תוֹעֶלֶת`,
    `ידידותי למשתמש`,
    `עֶמֶק`,
    `ערך`,
    `שׁוֹנִים`,
    `צִמחוֹנִי`,
    `רכב`,
    `ניצחון`,
    `אַלִימוּת`,
    `ויראלי, מתפשט במהירות באינטרנט`,
    `וירטואלי`,
    `חָזוֹן`,
    `מתנדב/ת`,
    `ארנק`,
    `בזבוז`,
    `חלש`,
    `חֲתוּנָה`,
    `מפורסם`,
    `מערבי`,
    `מה לגבי ...?`,
    `מה אם …?`,
    `מה קורה?`,
    `איזה/איזו/אילו`,
    `מי`,
    `מִי שזה לא יהיה`,
    `לנצח`,
    `לנגב, ניגוב`,
    `לאחל למישהו הצלחה`,
    `להתפלא`,
    `יער`,
    `מקום עבודה`,
    `יצירה`,
    `היה יכול לקרות`,
    `להעדיף`,
    `אכפת לך ...?`,
    `לַעֲטוֹף`,
    `ליצור`,
    `כתוב`,
    `עדיין`,
    `נוֹעַר`,
    `אֵזוֹר`
]